ALTER TABLE incidentes
ADD COLUMN IF NOT EXISTS condicion_meteorologica VARCHAR(100),
ADD COLUMN IF NOT EXISTS condicion_luz VARCHAR(50),
ADD COLUMN IF NOT EXISTS visibilidad_millas DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS viento_kt DOUBLE PRECISION;
